clear;close;clc;
t1=0:49;
x=sin(0.1*pi*t1);
xint=[x zeros(1,200-length(x))];
t2=0:199;
figure(1);
subplot(211);
plot(t1,x,'-o');
hold on;
plot(t2,xint);
xlabel('Time/s');
ylabel('Amplitude');
legend('x1','x2');
subplot(212);
[fx1,w1]=DTFTsamples(x);
plot(w1,abs(fx1));
hold on;
[fx2,w2]=DTFTsamples(xint);
plot(w2,abs(fx2));
xlabel('NAF/\pi');
ylabel('Magnitude');
legend('x1','x2');
